### ISSUE TITLE
Issue with page `src/pages/start/2.nix-run.mdx`

### ISSUE THREAD

**Issue by enterprisey** [DeterminateSystems/zero-to-nix#158]
Page says:

> It used the nixpkgs#ponysay [flake reference](https://zero-to-nix.com/concepts/flakes#references)

However, I think "nixpkgs" is the flake reference part, not the whole string. (Or if I'm wrong, at least it's inconsistent with the next page, where it does say `nixpkgs` is the flake reference.)

Thank you all for making this awesome guide.

**Comment by cole-h** [comment]
I think you're right; that should probably be "flake installable" or just "installable".
