### ISSUE TITLE
Export to .epub?

### ISSUE THREAD

**Issue by d33tah** [DeterminateSystems/zero-to-nix#162]
Thanks for creating this! Is there a way to export all the documentation in a linear ebook format?

**Comment by lucperkins** [comment]
@d33tah That would be nice but quite an undertaking to wrangle the current format (static HTML with a lot of interactive goodies) into epub. If you're aware of any tools or platforms that would simplify that, we're all ears!

**Comment by d33tah** [comment]
@lucperkins apologies, I didn't consider interactivity - I only took a look at some first pages and they seemed mostly static. I guess that the issue can be closed then!

**Comment by lucperkins** [comment]
@d33tah No need to apologize! I think it's a reasonable request and it may possible to have an epub build that doesn't have the interactive bits. I'll look into it! I'd say it's probably unlikely that this would be feasible without a ton of work but certainly worth exploring.

**Comment by lucperkins** [comment]
@d33tah I've done some research and I'm going to close this for now as a `WONTFIX`. I think it's a great suggestion but it would require some pretty sweeping changes. I'd love it if there were a tool that could handle something like this with aplomb. Maybe my next side project :devil: Thanks a ton for your input and if we reconsider I'll let you know :heart:
