### ISSUE TITLE
Issue with page `src/pages/concepts/nixos.mdx`

### ISSUE THREAD

**Issue by bew** [DeterminateSystems/zero-to-nix#168]
At the end of that page, it says:
`You can update a NixOS installation to a new release in configuration.nix using the system.stateVersion parameter.`

But that is quite misleading, the stateVersion is not really the way to update your nixos system 👀

**Comment by lucperkins** [comment]
Good call! I'm going to simply remove the mention for now while also noting that we'd like to document this better soon.
