### ISSUE TITLE
Development environments, `mkShell` and setup hooks

### ISSUE THREAD

**Issue by FRidh** [DeterminateSystems/zero-to-nix#180]
`mkShell` is essentially just `stdenv.mkDerivation` and thus for inputs you add the setup hooks get run. Looking at the Python example:

```
      # Development environment output
      devShells = forAllSystems ({ pkgs }: {
        default = pkgs.mkShell {
          # The Nix packages provided in the environment
          packages = with pkgs; [
            python311 # Python 3.11
            virtualenv # Virtualenv
            python311Packages.pip # The pip installer
          ];
        };
```
it means the Python hook is executed which sets `PYTHONPATH`. This is not desirable if you happen to pull in a Python application as well as it messes up your `sys.path`. Hence a better solution is to not add packages directly to `packages` and instead wrap them in a `buildEnv`, such as `python.withPackages`.

```
      # Development environment output
      devShells = forAllSystems ({ pkgs }: {
        default = pkgs.mkShell {
          # The Nix packages provided in the environment
          packages = [ (pkgs.python311.withPackages(ps: with ps; [ virtualenv pip ])) ];
        };
```
Granted, it looks more complex, but it is no fun when people come in with the same issues/questions because of examples they found.

**Comment by lucperkins** [comment]
Thanks a ton, @FRidh! I'm not always super up to speed on using Nix inside of specific language communities, so this kind of pointer is a huge help.
