### ISSUE TITLE
Issue with page `src/pages/start/2.nix-run.mdx`

### ISSUE THREAD

**Issue by 13013SwagR** [DeterminateSystems/zero-to-nix#223]
## Problem
When running `echo "Hello Nix" | nix run "nixpkgs#ponysay"`
I get the following error
```
error: experimental Nix feature 'nix-command' is disabled; use '--extra-experimental-features nix-command' to override
```
then when I run `echo "Hello Nix" | nix run "nixpkgs#ponysay" --extra-experimental-features nix-command`
I get the following error
```
error: experimental Nix feature 'flakes' is disabled; use '--extra-experimental-features flakes' to override
```
and when I run `echo "Hello Nix" | nix run "nixpkgs#ponysay" --extra-experimental-features flakes --extra-experimental-features nix-command`  

It works!

## Expected behavior/documentation
The tutorial should provide the proper Nix configuration to avoid those errors or at least add notes on how to cleanly solve them. 

## References
I installed Nix with this [tutorial](https://determinate.systems/posts/nix-on-the-steam-deck)

**Comment by lucperkins** [comment]
Our intention is that readers go through the quick start from start to finish. If you install Nix using Nix Installer and the instructions [here](https://zero-to-nix.com/start/install) then flakes are enabled by default. In that particular tutorial, the sentence immediately preceding that command states "In the last section, we installed Nix using Nix Installer..."
