### ISSUE TITLE
link in cookie notice invisible while hovered in bright mode

### ISSUE THREAD

**Issue by das-g** [DeterminateSystems/zero-to-nix#226]
### To reproduce:

1. Go to https://zero-to-nix.com/ for the first time (or with a fresh browser profile, e.g. in private mode).
2. In case you see the page in dark mode, switch to bright mode (by clicking the yellow sun icon at the top right or via your browser or OS setting).
3. Note the cookie notice at the bottom left.
   ![image](https://user-images.githubusercontent.com/97746/218270921-90edc321-682c-4603-97e6-bb1d8a90287f.png)
   Hover over the link "[privacy policy](https://determinate.systems/privacy)" in it.

#### Expected

Link has a different color while hovered (or is otherwise highlighted as an active, interaction-capable element), but remains legible.

#### Observed

Link is completely invisible while hovered, probably due to changing to the box's background color.

![Bildschirmfoto von Bildschirmaufzeichnung vom 2023-02-11, 18-05-04 webm](https://user-images.githubusercontent.com/97746/218271211-e88fbc4c-c988-4571-a28a-65ff82bd0a8f.png)

### Browser and System

Reproduced on:
- Mozilla Firefox 109.0.1 (64-bit)
- ungoogled-chromium 109.0.5414.120

Output of `nix-info -m`:
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.91, NixOS, 23.05 (Stoat), 23.05pre451105.06999209d7a`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.2`
 - channels(root): `"nixos, nixos-unstable"`
 - channels(das-g): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by lucperkins** [comment]
@das-g We're not exactly über-professional graphic designers but I think it's better now 😄 Thanks for reporting!
