### ISSUE TITLE
DNS Issue with install.determinate.systems?

### ISSUE THREAD

**Issue by eventualbuddha** [DeterminateSystems/zero-to-nix#232]
```
$ curl install.determinate.systems
curl: (6) Could not resolve host: install.determinate.systems
```

I tried to follow the instructions at the website to install Nix, got an error similar to the one above. Going to that domain in the browser also fails.

**Comment by lucperkins** [comment]
Hmmm, I'm not able to reproduce this. Is this still an issue for you?

**Comment by eventualbuddha** [comment]
Weird, works now.

**Comment by lucperkins** [comment]
Okay, good to hear!
