### ISSUE TITLE
Question around page `src/pages/start/1.install.mdx`

### ISSUE THREAD

**Issue by Rukomoynikov** [DeterminateSystems/zero-to-nix#235]
Hey there. 

Thanks for the site and instructions. Though I just started my journey, I have one question. 

On the mentioned page, you write about the advantages of customised nix installer, but what if I already installed the system with the help of the original installer? Do you know if I can run customised on top of my system?

This info would be helpful on this page.

Max.

**Comment by CyrusYip** [comment]
Enabling flakes in [nix.conf](https://nixos.org/manual/nix/stable/command-ref/conf-file.html) should be enough for you to continue.

```
experimental-features = nix-command flakes
```

I added the code in `~/.config/nix/nix.conf`.
