### ISSUE TITLE
Issue with page `src/pages/start/1.install.mdx`

### ISSUE THREAD

**Issue by hussainweb** [DeterminateSystems/zero-to-nix#236]
I used this page to install Nix and I think it installs fine. However, when I open a new terminal and try to run nix, it doesn't work (unknown command). I am guessing it is not added to PATH.

It works once I run this command as directed by the installer.
```
. /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.fish
```

But this works only for the current session. After this, `nix --version` works fine in the current session which tells me Nix is installed, but not set in the path. I couldn't find any other issue about this and hence creating this one.

While this gets fixed (I have no idea how), it would be good to also know how I can manually do this for now. Is it enough for me to `source` this file from my `config.fish`?

**Comment by hussainweb** [comment]
Fixed in https://github.com/DeterminateSystems/nix-installer/pull/267

**Comment by lucperkins** [comment]
@hussainweb Thanks for reporting! Great to see this get worked out 😄
