### ISSUE TITLE
Issue with page `src/pages/concepts/sandboxing.mdx`

### ISSUE THREAD

**Issue by CyrusYip** [DeterminateSystems/zero-to-nix#240]
The URL of `provenance` is missing.

<img width="442" alt="image" src="https://user-images.githubusercontent.com/60951091/221754494-6dd72ecb-1db3-47b7-b0d6-05ac07e8ab53.png">

**Comment by jowj** [comment]
Saw this myself. I'm not...really familiar with MDX? But just based on what I saw from the other files I think I have a a fix. See [my pr](https://github.com/DeterminateSystems/zero-to-nix/pull/243).

**Comment by lucperkins** [comment]
Fixed by #243. For future reference, links in MDX don't work any differently from plain Markdown!
