### ISSUE TITLE
SSL connect error while running ponysay example

### ISSUE THREAD

**Issue by mauricioabreu** [DeterminateSystems/zero-to-nix#251]
## Context

I'm trying out nix following the guide and this page has an example of running the _ponysay_ program

https://zero-to-nix.com/start/nix-run

## How to reproduce

MacOS
M1 (ARM64)

`echo "Hello Nix" | nix run "nixpkgs#ponysay"`

> warning: error: unable to download 'https://channels.nixos.org/flake-registry.json': SSL connect error (35); retrying in 272 ms
warning: error: unable to download 'https://channels.nixos.org/flake-registry.json': SSL connect error (35); retrying in 643 ms
warning: error: unable to download 'https://channels.nixos.org/flake-registry.json': SSL connect error (35); retrying in 1298 ms
warning: error: unable to download 'https://channels.nixos.org/flake-registry.json': SSL connect error (35); retrying in 2607 ms
error: unable to download 'https://channels.nixos.org/flake-registry.json': SSL connect error (35)

I'm not using any corporate proxies.
I can acess the `https://channels.nixos.org/flake-registry.json` through browser (Firefox) anyways.

**Comment by lucperkins** [comment]
Are you still having this issue?

**Comment by mauricioabreu** [comment]
Yes @lucperkins but I created a new issue [in the right repository](https://github.com/DeterminateSystems/nix-installer/issues/370). I think this one could be closed, right?

**Comment by lucperkins** [comment]
@mauricioabreu Ah! Sorry, I didn't catch that. Thanks a lot for reporting both here and in the nix-installer repo!
