### ISSUE TITLE
`nix install` is not a command?

### ISSUE THREAD

**Issue by rudesome** [DeterminateSystems/zero-to-nix#254]
what is meant by "a `nix install` command"?

https://github.com/DeterminateSystems/zero-to-nix/blob/e61a408ec0d57e2f3516eb9c5ffa2b088841cf89/src/pages/start/2.nix-run.mdx?plain=1#L44

**Comment by lucperkins** [comment]
It's meant as a hypothetical. There is no `nix install` command, and that's the what the sentence is trying to convey. You don't need to `nix some-install-command booper && booper`. You can just `nix run`.

**Comment by aleksandersumowski** [comment]
I would spell it out explicitly. I've tried `nix install` after reading this fragment 😅

**Comment by jcrben** [comment]
Not only should it be spelled out explicitly, but the idea that you just `nix run everything` is counterintuitive. The overall  experience of going through zero-to-nix feels targeted to project-specific developer environments but even devs want some globally installed programs.

**Comment by lucperkins** [comment]
The issue from our perspective is that `nix profile install` doesn't play nicely with tools like Home Manager and problems with it are common enough, in our experience, that we've opted not to include it in Z2N. But I'll revisit the command and see if things have improved.

**Comment by jcrben** [comment]
@lucperkins that's fair but if all you're going to say about installing things is to use "nix run"  you need to address upfront the obvious question that occurs to a developer around how that works with garbage collection. I don't know a lot about it but it feels like an ephemeral run and sometimes people want a persistent install.

Also keep in mind just how project-focused zero-to-nix is and think about addressing that upfront somewhere to help people who aren't hacking on specific projects understand how this might be able to help them or not.

Personally I'm a user of nix more for foundational operating system tooling than project-specific tooling. I've got a lot of language-specific stuff + devcontainers for project-specific tools.
