### ISSUE TITLE
Chapter 3: flake in non empty-directory

### ISSUE THREAD

**Issue by alper** [DeterminateSystems/zero-to-nix#260]
I'm following along until this bit:

> To get started in your Rust project, create an empty directory and initialize a flake template

So I thought because it's about a Rust project I could do the same in the non-empty directory of an existing Rust project. This however causes it to catastrophically error without recovery.

Is there a reason why the directory should be empty?

**Comment by lucperkins** [comment]
That's because the template is a full-fledged Rust project. If you initialize it in the current directory, it overrides any existing project files.

**Comment by alper** [comment]
> So I thought because it's about a Rust project I could do the same in the non-empty directory of an existing Rust project. This however causes it to catastrophically error without recovery.

I fixed this by adding the flake.nix to git which seems to be necessary for it to be picked up and copied to the nix store in a git project.
