### ISSUE TITLE
How would one make an environment with specific versions of packages tied together? 

### ISSUE THREAD

**Issue by frencojobs** [DeterminateSystems/zero-to-nix#282]
This maybe doesn't concern the repo, but, I'm trying out the tutorial (on how to use `flake.nix` to configure a development environment) and I'm trying to configure an environment for a project. But I need to use specific versions for certain packages for the project. Otherwise it doesn't work due to the nature of the concerning project. Let's say, as an example, I need packages `A`, `B` and `C`. I need `v1` of A, `v2` of B and `v3` of C. How can one achieve such configuration?

I thought that would be a common/popular use-case/requirement for a lot of projects so I thought I could just maybe specify the versions like `{ derivation = pkgs.git; version = "1.2.3" }` but it seems there's no such API.

The only way I could manage was to manually find the git commit number at which the package I want is at the version I want, and then to add it as a separate input. Like,

```nix
inputs = {
  nixpkgs-for-A = "github:NixOS/nixpkgs/v1commit...";
  nixpkgs-for-B = "github:NixOS/nixpkgs/v2commit...";
  nixpkgs-for-C = "github:NixOS/nixpkgs/v3commit...";
}
```

But I have more than 3 packages, and this approach easily becomes unmaintainable. It can't be the optimal solution. Any advice?

**Comment by lucperkins** [comment]
@frencojobs You may find this search engine helpful: https://lazamar.co.uk/nix-versions/
