### ISSUE TITLE
Issue with page `src/pages/start/3.nix-develop.mdx` - `unsupported tarball input attribute 'rev'`

### ISSUE THREAD

**Issue by thanhnguyen2187** [DeterminateSystems/zero-to-nix#308]
Hi!

Many thanks for the awesome learning source!

I used the command provided in the lesson:

```shell
nix develop "github:DeterminateSystems/zero-to-nix#example"
```

But it raised:

```
error: unsupported tarball input attribute 'rev'
(use '--show-trace' to show detailed location information)
```

Adding `--show-trace` yields:

```
error:
       … while updating the lock file of flake 'github:DeterminateSystems/zero-to-nix/22a258b8a2b7730e294ac5886a23eab94bcac794'

       error: unsupported tarball input attribute 'rev'
```

Do you have any idea what's the problem behind?

Thanks!

**Comment by thanhnguyen2187** [comment]
Not sure if it helps, but I'm using NixOS `23.05`. Running `nix --version` yields `nix (Nix) 2.13.3`.

**Comment by lucperkins** [comment]
We recommend upgrading Nix to the 2.18.* series by running `nix upgrade-nix` (you may need `sudo`)
