### ISSUE TITLE
Issue on the nix-develop guide 3

### ISSUE THREAD

**Issue by Joshua-Hwang** [DeterminateSystems/zero-to-nix#312]
Hi,

I'm not sure if I'm missing something from the previous guides. When I run the first line in [the guide](https://zero-to-nix.com/start/nix-develop) this is my result.
```
joshua@nixos ~> nix --version
nix (Nix) 2.13.6
joshua@nixos ~> nix develop "github:DeterminateSystems/zero-to-nix#example" --show-trace
error:
       … while updating the lock file of flake 'github:DeterminateSystems/zero-to-nix/1f79c82aa98f62134bd8d505cbdfbfe013afeedc'

       error: cannot write modified lock file of flake 'github:DeterminateSystems/zero-to-nix' (use '--no-write-lock-file' to ignore)
```

Am I missing something obvious?

**Comment by lucperkins** [comment]
You'll need to upgrade Nix, as 2.13.* is pretty dated at this point: https://nixos.org/manual/nix/stable/command-ref/new-cli/nix3-upgrade-nix
