### ISSUE TITLE
Issue with the output of code provided by page `src/pages/start/3.nix-develop.mdx`

### ISSUE THREAD

**Issue by chillcicada** [DeterminateSystems/zero-to-nix#363]
it's not a problem with the page itself.

after run `nix develop "https://flakehub.com/f/DeterminateSystems/zero-to-nix/*#hook"` which the page provided, it echoes:

```txt
Congrats! You just triggered a shell hook for a Nix development environment.
Run "exit" to exit this environment.
Then run "nix develop github:DeterminateSystems/zero-to-nix#hook" again to re-trigger this hook.
```

i think the uri should be `github:DeterminateSystems/zero-to-nix/*#hook`, not `github:DeterminateSystems/zero-to-nix#hook`.

**Comment by adamjsawicki** [comment]
@chillcicada just popping in here, and quite new to the Nix community myself, so take with a grain of salt!

It seems like in the first URL, we're targeting **FlakeHub**, and somewhere in resolving that, `nix develop` is able to interpret the wildcard of `*` and pulls the latest version of the flake  `hook` under _DeterminateSystems'_ GH user and `zero-to-nix` repo name but that is actually _stored_ on **FlakeHub**.

However, in the second URI, we're actually very specifically targetting the attribute inside the flake named `hook`, specified [here](https://github.com/DeterminateSystems/zero-to-nix/blob/5fad4d6b5459a8058942d1df1cebaf44a4c150c4/nix/shell/example.nix#L12-L18) - which is **not** accessed using a wildcard.

In fact, if you run the command with the URI you recommended, you will get the following:

```
error: in URL 'github:DeterminateSystems/zero-to-nix/*#hook', '*' is not a commit hash or branch/tag name
```

Hope this helps!

**Comment by chillcicada** [comment]
yes, you are right. i wasn't making a test in the shell at that time
