### ISSUE TITLE
`nix` not found after starting a new shell after running the installer on MacOS

### ISSUE THREAD

**Issue by CobyPear** [DeterminateSystems/zero-to-nix#375]
I'm running MacOS 15.0 (24A335)

I have tried installing and reinstalling a few times now.

If I run the command `. /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh` right after the install script, things work until I close my terminal. Then `nix` can't be found. Even if I manually add the path to the nix-profile to my `$PATH`, I can't run anything that I install with `nix profile install` so something is definitely not working correctly.

The installer mentions restarting the shell instead of running `. /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh` but if I do that `nix` can't be found at all.

Let me know if there is anything else I can provide to help debug.

**Comment by lucperkins** [comment]
@CobyPear You'll need to run that every time you open a new shell, for example by adding something like this to your `bashrc` or related file:

```shell
if [ -e '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh' ]; then
  . '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh'
 fi
```

**Comment by CobyPear** [comment]
@lucperkins I can see the following in my `/etc/zshrc` added by the install script however it doesn't work:

```sh
# Nix
if [ -e '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh' ]; then
    . '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh'
fi
# End Nix
```

It seems like `nix` doesn't get properly added to the `$PATH` on MacOS.
