### ISSUE TITLE
issue running the dev environment on opensuse 15.5

### ISSUE THREAD

**Issue by junelac** [DeterminateSystems/zero-to-nix#378]
Hello,

I started to follow the guide https://zero-to-nix.com/ in my opensuse 15.5, and got stuck at the point of trying the development environment wth this error

```
nix develop "https://flakehub.com/f/DeterminateSystems/zero-to-nix/*#example"                                                                                                                                                                           ─╯

mktemp: /lib64/libattr.so.1: version `ATTR_1.3' not found (required by mktemp)
mktemp: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by mktemp)
mktemp: /lib64/libc.so.6: version `GLIBC_2.33' not found (required by mktemp)
mktemp: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by mktemp)
mktemp: /lib64/libc.so.6: version `GLIBC_2.38' not found (required by mktemp)
rm: /lib64/libattr.so.1: version `ATTR_1.3' not found (required by rm)
rm: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by rm)
rm: /lib64/libc.so.6: version `GLIBC_2.33' not found (required by rm)
rm: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by rm)
rm: /lib64/libc.so.6: version `GLIBC_2.38' not found (required by rm)

```

As a note, the first time I tried I got stuck at the 'Run a program with nix', it was stuck in the download/installation phase, but uninstalling and reinstalling nix made it works.  

Also I got this warning during the install:

WARN SelfTest([ShellFailed { shell: Zsh, command: "\"zsh\" \"-ic\" \"nix build --option substitute false --no-link --expr \\'derivation { name = \\\"self-test-zsh-1730213883388\\\"; system = \\\"x86_64-linux\\\"; builder = \\\"/bin/sh\\\"; args = [\\\"-c\\\" \\\"echo hello > \\\\$out\\\"]; }\\'\"", output: Output { status: ExitStatus(unix_wait_status(32512)), stdout: "", stderr: "nix: searching ... \r nix: command not found                    \n" } }])

A last comment: uninstalling worked perfectly and I really like the explain option that shows what change are going to be done
thanks !

**Comment by junelac** [comment]
Hi, I had the opportunity to do some test and the issue was somewhere in my .bashrc or .bash_profile. I didn't look into the details since I have not used bash for years, but there was something that prevented nix (and thus the develop environment) to access the libraries.

**Comment by lucperkins** [comment]
@junelac That's great to hear! So glad you got this figured out
